# =========================
# DATABASE (MySQL)
# =========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


# =========================
# EMAIL (SendGrid - NO SMTP)
# =========================
app.email.from=${APP_EMAIL_FROM}
app.email.enabled=true

# SendGrid API Key (IMPORTANT)
SENDGRID_API_KEY=${SENDGRID_API_KEY}


# =========================
# CLOUDINARY
# =========================
cloudinary.cloud_name=dyekhgyhp
cloudinary.api_key=522485992315636
cloudinary.api_secret=${CLOUDINARY_SECRET}


# =========================
# PAYMENTS (Mock / Future use)
# =========================
app.payments.provider=MOCK
app.payments.currency=INR

app.stripe.secretKey=
app.stripe.webhookSecret=

app.razorpay.keyId=
app.razorpay.keySecret=